### ISSUE TITLE
[Bug] Unable to parse unix icon-path

### ISSUE THREAD

**Issue by Fooughhy** [lextm/windowsterminal-shell#6] opened 2020-05-10 20:23 UTC
The Windows Terminal is able to recognize both unix paths and escaped windows paths (`C:\\Git\\etc\\etc.ico` and `C:/Git/etc/etc.ico`) for their icon paths.
This script, however, only seems to work with the former way, i.e `C:\\Git\\etc\\etc.ico`.

**Comment by lextm** [comment] 2020-05-10 23:30
I cannot reproduce this when I set the icon as
```
      {
        "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
        "hidden": false,
        "name": "PowerShell",
        "icon": "c:/Program Files/Git/mingw64/share/git/git-for-windows.ico",
        "source": "Windows.Terminal.PowershellCore"
      }
```

I wonder what I missed, but this script as well as Windows Explorer seem to be happy supporting the `/` convention.

**Comment by Fooughhy** [comment] 2020-05-11 05:36
Hmm, I have a very similar profile... Will try to reproduce mine, but I have forked this repo to make very small changes (language and things) making me unsure if it's my changes which introduced this error. Also, the error produced by this behaviour I am explaining was very different from the other one I posted. I got an error complaining about the `$profileIcon` variable when calling the following:
> `CreateMenuItem "Registry::HKEY_CLASSES_ROOT\Directory\ContextMenus\MenuTerminal\shell\$guid" $name $profileIcon $command $false`
> `CreateMenuItem "Registry::HKEY_CLASSES_ROOT\Directory\ContextMenus\MenuTerminalAdmin\shell\$guid" $name $profileIcon $elevated $true`
> `CreateMenuItem "Registry::HKEY_CLASSES_ROOT\Drive\ContextMenus\MenuTerminal\shell\$guid" $name $profileIcon $command $false`
> `CreateMenuItem "Registry::HKEY_CLASSES_ROOT\Drive\ContextMenus\MenuTerminalAdmin\shell\$guid" $name $profileIcon $elevated $true`

**Comment by lextm** [comment] 2020-05-11 06:15
Then you need to debug your version. Close it now.

**Closed by lextm** 2020-05-11 06:15 UTC
