### ISSUE TITLE
Doesn't work with Powershell 7.1 Store Version

### ISSUE THREAD

**Issue by validatedev** [lextm/windowsterminal-shell#43] opened 2020-11-12 23:18 UTC
It says it is installed, but it seems that it's not.

**Comment by lextm** [comment] 2020-11-17 02:47
Duplicate of #37 

I don't know why Microsoft shipped PowerShell via the store, but you shouldn't use it at all as it comes with tons of limitation.

**Closed by lextm** 2020-11-17 02:47 UTC

**Comment by BobenHome** [comment] 2022-08-05 18:25
so what is final answer?

**Comment by lextm** [comment] 2022-08-06 00:30
By design. The Store version of PowerShell is not supported.
